# Generated by Django 3.0.3 on 2020-06-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(db_index=True, verbose_name='Current version of the schema for given content_type_id and object_id')),
                ('schema_hash', models.TextField(db_index=True, verbose_name='Meta data hash value of the schema')),
                ('content_type_id', models.PositiveIntegerField(db_index=True, verbose_name='Content type id of object')),
                ('object_id', models.PositiveIntegerField(db_index=True, verbose_name='Id of object')),
            ],
        ),
    ]
