# Generated by Django 3.0.3 on 2020-06-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemaversion',
            name='content_type_id',
        ),
        migrations.RemoveField(
            model_name='schemaversion',
            name='schema_hash',
        ),
        migrations.AddField(
            model_name='schemaversion',
            name='schema',
            field=models.TextField(default='FOOO', verbose_name='Unique name of the schema'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schemaversion',
            name='version',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Current version of the schema for given object_id'),
        ),
    ]
