# Generated by Django 3.0.3 on 2020-06-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeform', '0002_auto_20200612_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemaversion',
            name='schema',
            field=models.TextField(db_index=True, verbose_name='Unique name of the schema'),
        ),
    ]
