# Generated by Django 3.0.3 on 2020-06-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.TextField(help_text='Actor Name'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.TextField(verbose_name='Movie Title'),
        ),
    ]
